### ISSUE TITLE
moonlight-embedded not generating logs

### ISSUE THREAD

**Issue by NerdiCorgi** [krishenriksen/AnberPorts#13]
I'm having an issue with getting moonlight-embedded to do anything except exit or crash back to moonlight's main menu. It's not opening any dialog for me to pair it to PC, and regrettably not generating any logs I can investigate. I've uploaded a YT video showing it in action and can provide that link if it would be helpful.

**Comment by NerdiCorgi** [comment]
In trying to frame-by-frame my video, I found that moonlight-embedded is throwing LIBGL errors. I'm only about 70% confident on that, however, as they don't show in the video very clearly due to screen refresh rate vs the limited amount of time each line is on screen; but the "[LIBGL]" prefix seems pretty consistent.

**Comment by nikola-j** [comment]
I'm having the same issue, I'm on ArkOS 1.6, it worked on a previous version:
Here is the log:
```
librga:RGA_GET_VERSION:4.00,4.000000 
ctx=0x55bc501180,ctx->rgaFd=4 
fchmod (file attributes) error: Operation not permitted
warning:  cannot set modif./access times for ../moonlight-embedded/moonlight
          Operation not permitted
fchmod (file attributes) error: Operation not permitted
warning:  cannot set modif./access times for ../moonlight-embedded/settings.txt
          Operation not permitted
fchmod (file attributes) error: Operation not permitted
warning:  cannot set modif./access times for ../moonlight-embedded/gamecontrollerdb.txt
          Operation not permitted
chmod (directory attributes) error: Operation not permitted
fchmod (file attributes) error: Operation not permitted
warning:  cannot set modif./access times for ../moonlight-embedded/lib/libopus.so.0
          Operation not permitted
fchmod (file attributes) error: Operation not permitted
warning:  cannot set modif./access times for ../moonlight-embedded/lib/librockchip_vpu.so
          Operation not permitted
fchmod (file attributes) error: Operation not permitted
warning:  cannot set modif./access times for ../moonlight-embedded/lib/librockchip_mpp.so.1
          Operation not permitted
fchmod (file attributes) error: Operation not permitted
warning:  cannot set modif./access times for ../moonlight-embedded/lib/libmoonlight-common.so.4
          Operation not permitted
fchmod (file attributes) error: Operation not permitted
warning:  cannot set modif./access times for ../moonlight-embedded/lib/librockchip_mpp.so
          Operation not permitted
fchmod (file attributes) error: Operation not permitted
warning:  cannot set modif./access times for ../moonlight-embedded/lib/libXfixes.so.3
          Operation not permitted
fchmod (file attributes) error: Operation not permitted
warning:  cannot set modif./access times for ../moonlight-embedded/lib/librockchip_mpp.so.0
          Operation not permitted
fchmod (file attributes) error: Operation not permitted
warning:  cannot set modif./access times for ../moonlight-embedded/lib/libmoonlight-common.so
          Operation not permitted
fchmod (file attributes) error: Operation not permitted
warning:  cannot set modif./access times for ../moonlight-embedded/lib/libva-x11.so.2
          Operation not permitted
fchmod (file attributes) error: Operation not permitted
warning:  cannot set modif./access times for ../moonlight-embedded/lib/libmoonlight-common.so.2.4.10
          Operation not permitted
fchmod (file attributes) error: Operation not permitted
warning:  cannot set modif./access times for ../moonlight-embedded/lib/libgamestream.so.4
          Operation not permitted
fchmod (file attributes) error: Operation not permitted
warning:  cannot set modif./access times for ../moonlight-embedded/lib/librockchip_vpu.so.0
          Operation not permitted
fchmod (file attributes) error: Operation not permitted
warning:  cannot set modif./access times for ../moonlight-embedded/lib/libenet.so.7
          Operation not permitted
fchmod (file attributes) error: Operation not permitted
warning:  cannot set modif./access times for ../moonlight-embedded/lib/libmoonlight-rk.so
          Operation not permitted
fchmod (file attributes) error: Operation not permitted
warning:  cannot set modif./access times for ../moonlight-embedded/lib/librockchip_vpu.so.1
          Operation not permitted
fchmod (file attributes) error: Operation not permitted
warning:  cannot set modif./access times for ../moonlight-embedded/lib/libgamestream.so
          Operation not permitted
fchmod (file attributes) error: Operation not permitted
warning:  cannot set modif./access times for ../moonlight-embedded/lib/libva.so.2
          Operation not permitted
fchmod (file attributes) error: Operation not permitted
warning:  cannot set modif./access times for ../moonlight-embedded/lib/libgamestream.so.2.4.10
          Operation not permitted
fchmod (file attributes) error: Operation not permitted
warning:  cannot set modif./access times for ../moonlight-embedded/ip.txt
          Operation not permitted
warning:  cannot set modif./access times for ../moonlight-embedded/lib/
          Operation not permitted
warning:  cannot set permissions for ../moonlight-embedded/lib/
          Operation not permitted
warning:  set times/attribs failed for ../moonlight-embedded/lib/
chmod: changing permissions of '../Moonlight Embedded.sh': Operation not permitted
```

**Comment by skelph** [comment]
Same here worked on arkos 1.5 and works on 351elec but tried on numerous occasions installing resins talking clean image the lot Nadda m8.. same with any streaming  section gforce now stadia Luna the lot

**Comment by skelph** [comment]
update after a arkos update now a menu comes up but cant change any settings just reverts to  moonlight title screen, stadia gforce now luna all just revert to title ports menu

**Comment by nikola-j** [comment]
New version of AnberPorts works for me

**Comment by krishenriksen** [comment]
Should be fixed in latest version. Nvidia updated GFE, and this broke some stuff.

**Comment by SzalikDesigns** [comment]
if issue still occur please open new ticket, as it seems to work fine now
